name: make-main-pot

on:
  push:
    branches:
      - main
    paths:
      - "src/**/*"
  workflow_dispatch:

permissions:
  contents: write

env:
  TARGET_BRANCH: main

jobs:
  php-pot-file:
    name: Check for translation file updates
    runs-on: ubuntu-latest
    outputs:
      php-localize-file-update: ${{ steps.php_changed.outputs.isChanged }}
    steps:
      - name: Install gettext module
        run: sudo apt-get install -y gettext

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TARGET_BRANCH }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Generate main-php.pot file
        run: |
          find src -type f \( -name '*.php' \)  -print > list
          xgettext --files-from=list --keyword=_i --language=PHP --from-code=UTF-8 -o locale/common/main/main-php.pot

      - name: Remove pot metadata
        run: sed -i '1,19d' locale/common/main/main-php.pot

      - name: Verify main-php.pot changed
        uses: tj-actions/verify-changed-files@v9.2
        id: php_changed_files
        with:
          files: |
            locale/common/main/main-php.pot
          token: ${{ secrets.GH_TOKEN }}
          autocrlf: input
          separator: " "

      - name: Run step only when files change.
        id: php_changed
        if: steps.php_changed_files.outputs.files_changed == 'true'
        run: |
          echo "Changed files: ${{ steps.php_changed_files.outputs.changed_files }}"
          echo "::set-output name=isChanged::true"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.php_changed_files.outputs.files_changed == 'true'
        with:
          commit_message: make main-php.pot file
          file_pattern: locale/common/main/main-php.pot

  main-pot-file:
    name: Aggregate multiple pot files
    runs-on: ubuntu-latest
    needs: [php-pot-file]
    if: needs.php-pot-file.outputs.php-localize-file-update == 'true'

    steps:
      - name: Install gettext module
        run: sudo apt-get install -y gettext

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TARGET_BRANCH }}
          token: ${{ secrets.GH_TOKEN }}

      - name: POT Merge
        run: |
          msgcat locale/common/main/main-php.pot > locale/common/main/main.pot

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: make main.pot file
          file_pattern: locale/common/main/main.pot

  intermediate-files:
    name: Upsert intermediate language file for dev
    runs-on: ubuntu-latest
    needs: [php-pot-file, main-pot-file]
    steps:
      - name: Install gettext module
        run: sudo apt-get install -y gettext

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TARGET_BRANCH }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Merge latest template file to intermediate file
        run: |
          msgmerge -U locale/common/main/intermediate.po locale/common/main/main.pot 

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update intermediate language file for dev
          file_pattern: locale/common/main/intermediate.po
 