name: make-main-pot

on:
  push:
    branches:
      - i18n-weblate
    paths:
      - "src/main/**"
  pull_request:
    branches:
      - i18n-weblate
    paths:
      - "src/main/**"

permissions:
  contents: write

jobs:
  php-pot-file:
    name: Check for translation file updates
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scope: [main, admin, site]
    # outputs:
    #   php-localize-file-update: ${{ steps.php_changed.outputs.isChanged }}
    steps:
      - name: Install gettext module
        run: sudo apt-get install -y gettext

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: i18n-weblate

      - name: Create locale folder by scope
        run: |
          mkdir -p locale/${{matrix.scope}}/common/

      - name: Generate php.pot file
        run: |
          find src/${{matrix.scope}} -type f \( -name '*.php' \)  -print > list
          xgettext --files-from=list --keyword=_i --language=PHP --from-code=UTF-8 -o locale/${{matrix.scope}}/common/php.pot

      - name: Remove pot metadata
        run: sed -i '1,19d' locale/${{matrix.scope}}/common/php.pot

      - name: Upload new php-pot-file
        uses: actions/upload-artifact@v3
        with:
          name: changed-files-artifact
          path: locale/${{matrix.scope}}/common/php.pot

      # - name: Verify php.pot changed
      #   uses: tj-actions/verify-changed-files@v9.2
      #   id: php_changed_files
      #   with:
      #     files: |
      #       locale/${{matrix.scope}}/common/php.pot
      #     token: ${{ secrets.GH_TOKEN }}
      #     autocrlf: input
      #     separator: " "

      # - name: Run step only when files change.
      #   id: php_changed
      #   if: steps.php_changed_files.outputs.files_changed == 'true'
      #   run: |
      #     echo "Changed files: ${{ steps.php_changed_files.outputs.changed_files }}"
      #     echo "::set-output name=isChanged::true"

      # - name: Commit changes
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   if: steps.php_changed_files.outputs.files_changed == 'true'
      #   with:
      #     commit_message: make php.pot file
      #     file_pattern: locale/${{matrix.scope}}/common/php.pot

  main-pot-file:
    name: Aggregate multiple pot files
    runs-on: ubuntu-latest
    needs: [php-pot-file]
    strategy:
      matrix:
        scope: [main, admin, site]
    # if: needs.php-pot-file.outputs.php-localize-file-update == 'true'

    steps:
      - name: Install gettext module
        run: sudo apt-get install -y gettext

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: i18n-weblate

      - name: POT Merge
        run: |
          msgcat locale/${{matrix.scope}}/common/php.pot > locale/${{matrix.scope}}/common/main.pot

      - name: Upload new main-pot-file
        uses: actions/upload-artifact@v3
        with:
          name: changed-files-artifact
          path: locale/${{matrix.scope}}/common/main.pot

      # - name: Commit changes
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: make main.pot file
      #     file_pattern: locale/${{matrix.scope}}/common/main.pot

  intermediate-file:
    name: Upsert intermediate language file for dev
    runs-on: ubuntu-latest
    needs: [main-pot-file]
    strategy:
      matrix:
        scope: [main, admin, site]
    steps:
      - name: Install gettext module
        run: sudo apt-get install -y gettext

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: i18n-weblate
      
      - name: Touch intermediate file if not exists
        run: touch locale/${{matrix.scope}}/common/intermediate.po

      - name: Merge latest template file to intermediate file
        run: |
          msgmerge -U locale/${{matrix.scope}}/common/intermediate.po locale/${{matrix.scope}}/common/main.pot 
      
      - name: Upload new intermediate-file
        uses: actions/upload-artifact@v3
        with:
          name: changed-files-artifact
          path: locale/${{matrix.scope}}/common/intermediate.po

      # - name: Commit changes
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: update intermediate language file for dev
      #     file_pattern: locale/${{matrix.scope}}/common/intermediate.po

  commit_message:
    name: Upsert intermediate language file for dev
    runs-on: ubuntu-latest
    needs: [main-pot-file]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: i18n-weblate

      - uses: actions/download-artifact@v3
        with:
          name: changed-files-artifact
          path: locale
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./
      # - name: Commit changes
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   if: steps.php_changed_files.outputs.files_changed == 'true'
      #   with:
      #     commit_message: make php.pot file
      #     file_pattern: locale/${{matrix.scope}}/common/php.pot
 