name: make-main-pot

on:
  push:
    branches:
      - i18n-weblate
    paths:
      - "src/**/*"
  pull_request:
    branches:
      - i18n-weblate
    paths:
      - "src/**/*"

permissions:
  contents: write

jobs:
  verify:
    name: Check for translation file updates
    runs-on: ubuntu-latest
    outputs:
      php-localize-file-update: ${{ steps.php_changed.outputs.isChanged }}
    steps:
      - name: Install gettext module
        run: sudo apt-get install -y gettext

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: i18n-weblate

      # PHP
      - name: Generate main-php.pot file
        run: |
          find src -type f \( -name '*.php' \)  -print > list
          xgettext --files-from=list --keyword=_i --language=PHP --from-code=UTF-8 -o src/locale/common/main/main-php.pot

      - name: Remove pot metadata
        run: sed -i '1,19d' src/locale/common/main/main-php.pot

      - name: Verify main-php.pot changed
        uses: tj-actions/verify-changed-files@v9.2
        id: php_changed_files
        with:
          files: |
            src/locale/common/main/main-php.pot
          token: ${{ secrets.GH_TOKEN }}
          autocrlf: input
          separator: " "

      - name: Run step only when files change.
        id: php_changed
        if: steps.php_changed_files.outputs.files_changed == 'true'
        run: |
          echo "Changed files: ${{ steps.php_changed_files.outputs.changed_files }}"
          echo "::set-output name=isChanged::true"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.php_changed_files.outputs.files_changed == 'true'
        with:
          commit_message: make main-php.pot file
          file_pattern: src/locale/common/main/main-php.pot

  php:
    name: PHP POT file generate
    runs-on: ubuntu-latest
    needs: [verify]
    if: needs.verify.outputs.php-localize-file-update == 'true'

    steps:
      - name: Install gettext module
        run: sudo apt-get install -y gettext

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: i18n-weblate
      - run: git checkout HEAD^

      - name: POT Merge
        run: |
          msgcat src/locale/common/main/main-php.pot > src/locale/common/main/main.pot

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: make main.pot file
          file_pattern: src/locale/common/main/main.pot

  update:
    name: Creating an intermediate language file DEV
    runs-on: ubuntu-latest
    needs: [verify, php]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: POT Merge
        run: |
          rm src/locale/common/main/main.po
          cp src/locale/common/main/main.pot src/locale/common/main/main.po

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update dev i18n
          file_pattern: src/locale/common/main/main.po