name: make-main-intermediate

on:
  push:
    branches:
      - i18n-weblate
    paths:
      - "locale/common/**/*.pot"
  pull_request:
    branches:
      - i18n-weblate
    paths:
      - "locale/common/**/*.pot"

permissions:
  contents: write

jobs: 
  upsert:
    name: Upsert intermediate language file for dev
    runs-on: ubuntu-latest
    steps:
      - name: Install gettext module
        run: sudo apt-get install -y gettext

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: i18n-weblate

      - name: POT Merge
        run: |
          msgmerge -U locale/common/main/intermediate.po locale/common/main/main.pot 

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update intermediate language file for dev
          file_pattern: locale/common/main/intermediate.po