name: make-locale-mo

on:
  push:
    branches:
      - i18n-weblate
    paths:
      - "locale/**/*.po"
      - "!local/common/*"
  pull_request:
    branches:
      - i18n-weblate
    paths:
      - "locale/**/*.po"
      - "!local/common/*"

permissions:
  contents: write

jobs:
  update:
    name: Generate locale mo files
    runs-on: ubuntu-latest
    steps:
      - name: Install gettext module
        run: sudo apt-get install -y gettext

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: i18n-weblate

      - name: Convert mo files from po files
        run: |
          find -name \*.po -not -path "./locale/common/*" -execdir msgfmt main.po -o main.mo \;

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update mo files
          file_pattern: locale/**/*.mo