name: make-admin-pot

on:
  push:
    branches:
      - i18n-weblate
    paths:
      - "src/admin/**"
  pull_request:
    branches:
      - i18n-weblate
    paths:
      - "src/admin/**"

permissions:
  contents: write

env:
  scope: admin

jobs:
  php-pot-file:
    name: Check for translation file updates
    runs-on: ubuntu-latest
    outputs:
      php-localize-file-update: ${{ steps.php_changed.outputs.isChanged }}
    steps:
      - name: Install gettext module
        run: sudo apt-get install -y gettext

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: i18n-weblate

      - name: Generate php.pot file
        run: |
          find src/${{env.scope}} -type f \( -name '*.php' \)  -print > list
          xgettext --files-from=list --keyword=_i --language=PHP --from-code=UTF-8 -o locale/${{env.scope}}/common/php.pot

      - name: Remove pot metadata
        run: sed -i '1,19d' locale/${{env.scope}}/common/php.pot

      - name: Verify php.pot changed
        uses: tj-actions/verify-changed-files@v9.2
        id: php_changed_files
        with:
          files: |
            locale/${{env.scope}}/common/php.pot
          token: ${{ secrets.GH_TOKEN }}
          autocrlf: input
          separator: " "

      - name: Run step only when files change.
        id: php_changed
        if: steps.php_changed_files.outputs.files_changed == 'true'
        run: |
          echo "Changed files: ${{ steps.php_changed_files.outputs.changed_files }}"
          echo "::set-output name=isChanged::true"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.php_changed_files.outputs.files_changed == 'true'
        with:
          commit_message: make php.pot file
          file_pattern: locale/${{env.scope}}/common/php.pot

  main-pot-file:
    name: Aggregate multiple pot files
    runs-on: ubuntu-latest
    needs: [php-pot-file]
    if: needs.php-pot-file.outputs.php-localize-file-update == 'true'

    steps:
      - name: Install gettext module
        run: sudo apt-get install -y gettext

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: i18n-weblate

      - name: POT Merge
        run: |
          msgcat locale/${{env.scope}}/common/php.pot > locale/${{env.scope}}/common/main.pot

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: make main.pot file
          file_pattern: locale/${{env.scope}}/common/main.pot

  intermediate-files:
    name: Upsert intermediate language file for dev
    runs-on: ubuntu-latest
    needs: [php-pot-file, main-pot-file]
    steps:
      - name: Install gettext module
        run: sudo apt-get install -y gettext

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: i18n-weblate

      - name: Merge latest template file to intermediate file
        run: |
          msgmerge -U locale/${{env.scope}}/common/intermediate.po locale/${{env.scope}}/common/main.pot 

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update intermediate language file for dev
          file_pattern: locale/${{env.scope}}/common/intermediate.po
 